"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _movies_card from './movies-card.bones.json'

registerBones({
  "movies-card": _movies_card,
})
